# Generated by Django 2.2.6 on 2019-10-03 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NoticeText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=500)),
                ('content', models.TextField()),
                ('date', models.DateField()),
                ('isStaff', models.BooleanField(default=False)),
                ('isStudent', models.BooleanField(default=False)),
                ('isTeacher', models.BooleanField(default=False)),
                ('isAll', models.BooleanField(default=False)),
                ('isResearcher', models.BooleanField(default=False)),
                ('isApproved', models.BooleanField(default=False)),
            ],
        ),
    ]
