# Generated by Django 2.2.6 on 2019-10-13 18:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('macsdept', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticetext',
            name='pdf',
            field=models.FileField(default=django.utils.timezone.now, upload_to='notice/pdfs'),
            preserve_default=False,
        ),
    ]
