# Generated by Django 2.2.6 on 2019-11-09 12:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('macsdept', '0003_userprofile'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeaveApplication',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('isCasual', models.BooleanField(default=False)),
                ('isEarned', models.BooleanField(default=False)),
                ('isCommuted', models.BooleanField(default=False)),
                ('isCompensatory', models.BooleanField(default=False)),
                ('firstDate', models.DateField()),
                ('lastDate', models.DateField()),
                ('isApprove', models.BooleanField(default=False)),
                ('approveDate', models.DateField()),
                ('reason', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
