# Generated by Django 2.2.6 on 2019-11-09 13:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('macsdept', '0004_leaveapplication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='leaveapplication',
            name='approveDate',
        ),
        migrations.CreateModel(
            name='LeaveStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approveDate', models.DateField()),
                ('leave', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='macsdept.LeaveApplication')),
            ],
        ),
    ]
