# Generated by Django 2.2.6 on 2019-11-09 15:51

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('macsdept', '0005_auto_20191109_1840'),
    ]

    operations = [
        migrations.AddField(
            model_name='leaveapplication',
            name='requestDate',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
